In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good devoloper',
    'Understand the simple rnn',
    'you are a nice media editor'
]

In [3]:
### Defining the vocabulary size
voc_size = 10000

In [4]:
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3168, 4108, 4718, 2641],
 [3168, 4108, 4718, 165],
 [3168, 9458, 4718, 1489],
 [5234, 7065, 7929, 2545, 9329],
 [5234, 7065, 7929, 2545, 5673],
 [6267, 3168, 3096, 7639],
 [7804, 4973, 7929, 5077, 6612, 8730]]

In [5]:
### Word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

We have to make all the sentences to the equal size while training with rnn  
at last all the words that are going it will be fixed number of time stamps based on the sentence size.so,pad_sequences is useful for this problem

In [6]:
import numpy as np

In [7]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3168 4108 4718 2641]
 [   0    0    0    0 3168 4108 4718  165]
 [   0    0    0    0 3168 9458 4718 1489]
 [   0    0    0 5234 7065 7929 2545 9329]
 [   0    0    0 5234 7065 7929 2545 5673]
 [   0    0    0    0 6267 3168 3096 7639]
 [   0    0 7804 4973 7929 5077 6612 8730]]


Parameter -> padding='pre'  
***Definition:*** Specifies where padding should be applied.  
- 'pre' means that zeros will be added before each sequence (at the beginning), effectively shifting the sequence to the right.  
- 'post' would mean adding zeros after each sequence (at the end).

In [8]:
### Feature Representation
dim = 10

In [9]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

2024-08-02 19:41:42.276390: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2024-08-02 19:41:42.276445: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2024-08-02 19:41:42.276451: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2024-08-02 19:41:42.276996: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:303] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-08-02 19:41:42.277518: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:269] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [11]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 253ms/step


2024-08-02 19:41:47.484997: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


array([[[-0.03977865, -0.02560253,  0.0412815 ,  0.04533552,
          0.02591827, -0.03808495,  0.03595482,  0.04874134,
          0.02905948, -0.03039222],
        [-0.03977865, -0.02560253,  0.0412815 ,  0.04533552,
          0.02591827, -0.03808495,  0.03595482,  0.04874134,
          0.02905948, -0.03039222],
        [-0.03977865, -0.02560253,  0.0412815 ,  0.04533552,
          0.02591827, -0.03808495,  0.03595482,  0.04874134,
          0.02905948, -0.03039222],
        [-0.03977865, -0.02560253,  0.0412815 ,  0.04533552,
          0.02591827, -0.03808495,  0.03595482,  0.04874134,
          0.02905948, -0.03039222],
        [ 0.01524209,  0.00430893,  0.01861085, -0.04522418,
         -0.0282833 ,  0.03581232, -0.02837986, -0.00123731,
         -0.0234367 ,  0.03000948],
        [-0.01293518,  0.01910306, -0.03742117, -0.0409364 ,
          0.04002668,  0.0357562 ,  0.02963156, -0.01412265,
         -0.04968293, -0.03702806],
        [ 0.01464441,  0.04219875, -0.04532   , -0.0

In [12]:
embedded_docs[0]

array([   0,    0,    0,    0, 3168, 4108, 4718, 2641], dtype=int32)

In [13]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 48ms/step


2024-08-02 19:41:50.926673: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


array([[-0.03977865, -0.02560253,  0.0412815 ,  0.04533552,  0.02591827,
        -0.03808495,  0.03595482,  0.04874134,  0.02905948, -0.03039222],
       [-0.03977865, -0.02560253,  0.0412815 ,  0.04533552,  0.02591827,
        -0.03808495,  0.03595482,  0.04874134,  0.02905948, -0.03039222],
       [-0.03977865, -0.02560253,  0.0412815 ,  0.04533552,  0.02591827,
        -0.03808495,  0.03595482,  0.04874134,  0.02905948, -0.03039222],
       [-0.03977865, -0.02560253,  0.0412815 ,  0.04533552,  0.02591827,
        -0.03808495,  0.03595482,  0.04874134,  0.02905948, -0.03039222],
       [ 0.01524209,  0.00430893,  0.01861085, -0.04522418, -0.0282833 ,
         0.03581232, -0.02837986, -0.00123731, -0.0234367 ,  0.03000948],
       [-0.01293518,  0.01910306, -0.03742117, -0.0409364 ,  0.04002668,
         0.0357562 ,  0.02963156, -0.01412265, -0.04968293, -0.03702806],
       [ 0.01464441,  0.04219875, -0.04532   , -0.04424753,  0.01203788,
        -0.0161484 , -0.02371566,  0.03694918